//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OTP_Details
    {
        public int OTP_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string OTP { get; set; }
        public System.DateTime GeneratedOn { get; set; }
        public System.DateTime ValidTill { get; set; }
    
        public virtual T_User T_User { get; set; }
    }
}
